name: Build JAR

on:
  push: 
    branches: 
      - main
      
  workflow_dispatch:

permissions:
  # contents: read
  # packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Generate release tag
      #   id: tag
      #   run: echo "::set-output name=release_tag::AutoBuild_$(date +"%Y.%m.%d_%H-%M")"

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Build jar
        run: |
          javac -sourcepath ./src/ -d ./target/ ./src/Main.java
          jar cfe JBomberMan.jar Main ./target/*.class 
          
      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: JBomberMan.jar 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: jar
        
      - uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 1
          delete_tags: true
          delete_tag_pattern: jar # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # with:
        #    tag_name: ${{ steps.tag.outputs.release_tag }}
        # repo: <owner>/<repoName> # defaults to current repo
        # keep_min_download_counts: 1 # Optional parameters
        # delete_expired_data: 10 # Optional parameters
        # delete_tag_pattern: beta # defaults to ""
